# Generated by Django 2.2.4 on 2019-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190908_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
