# Generated by Django 2.2.4 on 2019-09-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190908_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
