# Generated by Django 2.2.5 on 2019-09-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='industry_license',
            field=models.FileField(upload_to='manufacturer/profile/'),
        ),
    ]
