# Generated by Django 2.2.4 on 2019-09-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=11)),
                ('chassis_no', models.CharField(max_length=17)),
                ('engine_no', models.CharField(max_length=10)),
                ('fitness_validity', models.CharField(max_length=11)),
                ('fuel_type', models.CharField(max_length=10)),
                ('insurance_deadline', models.CharField(max_length=11)),
                ('maker', models.TextField()),
                ('model', models.TextField()),
                ('rc_status', models.CharField(max_length=10)),
                ('registration_authority', models.CharField(max_length=50)),
                ('vehicle_class', models.TextField()),
            ],
        ),
    ]
