# Generated by Django 2.2.4 on 2019-09-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0003_manufacturervehicledatasheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturervehicledatasheet',
            old_name='xls_file',
            new_name='file',
        ),
    ]
