# Generated by Django 2.2.4 on 2019-09-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_auto_20190913_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturervehicleinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
