# Generated by Django 2.2.5 on 2019-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0005_manufacturervehicleinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturervehicleinfo',
            name='price',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
