# Generated by Django 2.2.4 on 2019-09-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0006_manufacturervehicleinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturervehicleinfo',
            name='status',
            field=models.CharField(default='Not Registered', max_length=20),
        ),
    ]
