# Generated by Django 2.2.5 on 2019-09-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0007_auto_20190914_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManufacturerVehicleDataSheet',
        ),
        migrations.DeleteModel(
            name='ManufacturerVehicleInfo',
        ),
    ]
