# Generated by Django 2.2.5 on 2019-09-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0009_manufacturer_manufacturervehicledatasheet_manufacturervehicleinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
