# Generated by Django 2.2.5 on 2019-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0010_delete_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_contact', models.CharField(max_length=13)),
                ('owner_contact', models.CharField(max_length=13)),
                ('company_logo', models.FileField(default='hello.jpg', upload_to='manufacturer/logo/')),
                ('company_license', models.FileField(upload_to='manufacturer/license/')),
            ],
        ),
    ]
