# Generated by Django 2.2.5 on 2019-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0011_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='company_logo',
            field=models.FileField(upload_to='manufacturer/logo/'),
        ),
    ]
