# Generated by Django 2.2.5 on 2019-10-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0013_manufacturer_license_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
