# Generated by Django 2.2.5 on 2019-10-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0014_manufacturer_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
