# Generated by Django 2.2.5 on 2019-10-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0015_auto_20191003_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturervehicleinfo',
            name='maker',
        ),
    ]
