# Generated by Django 2.2.5 on 2019-10-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0016_remove_manufacturervehicleinfo_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturervehicleinfo',
            name='maker',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
