# Generated by Django 2.2.5 on 2019-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('husband_name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('birth_place', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact1', models.CharField(max_length=13)),
                ('contact2', models.CharField(max_length=13, null=True)),
                ('driving_license', models.FileField(upload_to='dealer/license/')),
            ],
        ),
    ]
