# Generated by Django 2.2.5 on 2019-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20191001_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='license_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
