# Generated by Django 2.2.5 on 2019-10-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_buyer_license_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='address2',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
