# Generated by Django 2.2.5 on 2019-10-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20191004_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='aadhar_no',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
