# Generated by Django 2.2.5 on 2019-10-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_auto_20191003_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='authorized_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealer',
            name='manufacturer_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
