# Generated by Django 2.2.5 on 2019-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_auto_20191004_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='manufacturer_name',
            new_name='authorized_brand',
        ),
        migrations.AddField(
            model_name='dealer',
            name='brand_names',
            field=models.TextField(max_length=65535, null=True),
        ),
    ]
