# Generated by Django 2.2.5 on 2019-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_auto_20191004_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='authorized_dealer',
            field=models.BooleanField(default=True),
        ),
    ]
