# Generated by Django 2.2.4 on 2019-09-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleData',
        ),
    ]
