# Generated by Django 2.2.5 on 2019-09-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20190921_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='industry_license',
            field=models.FileField(default='hello.jpg', upload_to='manufacturer/profile/'),
        ),
    ]
